# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1784aa4aced964299be2971f831d0b9427f83909df74647e6b4a017077418552805f9cd9ba51c9a1858317511e1ccfaba70b4a870de7f0c99c0bce27cde9b8fd

test:
  secret_key_base: e9cbccb2cd8cb49d32393a0c1904cd5512a80739bc979442173ae19233933dd3ad7c4e5427679feac095add7568ca90be90225e284b58a0e11180b5c13c81a5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
